//
//  DBColorNames.m
//  DBColorNames
//
//  Created by Daniel Beard on 10/16/14.
//  Copyright (c) 2014 DanielBeard. All rights reserved.
//

/*
 The MIT License (MIT)
 
 Copyright (c) 2014 Daniel Beard
 
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
 
 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 */

#import "DBColorNames.h"
#import <UIKit/UIKit.h>

static const NSString *kId = @"colorId";

@interface DBColorNames ()

@property (nonatomic, strong) NSDictionary *colorMap;

@end

@implementation DBColorNames

- (instancetype)init {
    self = [super init];
    if (self) {
        [self setupColorMap];
    }
    return self;
}

- (UIColor *)colorFromRGBFloat:(int)rgbValue {
    return [UIColor
            colorWithRed : ((float)((rgbValue & 0xFF0000) >> 16)) / 255.0
            green : ((float)((rgbValue & 0xFF00) >> 8)) / 255.0
            blue : ((float)(rgbValue & 0xFF)) / 255.0
            alpha : 1.0];
}

- (void)setupColorMap {
    self.colorMap = @{
                      @"blue": @{kId:@(0xacc2d9)},
                      @"green": @{kId:@(0x56ae57)},
                      @"yellow": @{kId:@(0xd99b82)},
                      @"brown": @{kId:@(0xd3b683)},
                      @"yellow": @{kId:@(0xc2b709)},
                      @"magenta": @{kId:@(0xd767ad)},
                      @"red": @{kId:@(0x850e04)},
                      @"lavendar": @{kId:@(0xefc0fe)},
                      @"grey": @{kId:@(0x5e9b8a)},
                      @"purple": @{kId:@(0xad03de)},
                      @"pink": @{kId:@(0xd99b82)},
                      @"orange": @{kId:@(0xca6b02)},
                      @"grey": @{kId:@(0x95a3a6)},
                      @"maroon": @{kId:@(0xa24857)},
                      @"purple": @{kId:@(0x825f87)},
                      @"bronze": @{kId:@(0xa87900)},
                      
                      };
}


- (NSString *)nameForColor:(UIColor *)color {
    
    CGFloat iR = 0.0f;
    CGFloat iG = 0.0f;
    CGFloat iB = 0.0f;
    CGFloat iA = 0.0f;
    
    [color getRed:&iR green:&iG blue:&iB alpha:&iA];
    
    CGFloat minDistance = CGFLOAT_MAX;
    NSString *colorKey = nil;
    
    for (NSString *key in self.colorMap) {
        @autoreleasepool {
            UIColor *currentColor = [self colorFromRGBFloat:[self.colorMap[key][kId] intValue]];
           
            CGFloat cR, cG, cB, cA = 0.0f;
            [currentColor getRed:&cR green:&cG blue:&cB alpha:&cA];
           
            // Calculate euclidean distance
            
            // Deltas
            CGFloat dR = iR - cR;
            CGFloat dG = iG - cG;
            CGFloat dB = iB - cB;
            
            CGFloat a = pow(dR, 2.0f);
            CGFloat b = pow(dG, 2.0f);
            CGFloat c = pow(dB, 2.0f);
            
            CGFloat d = sqrt(a + b + c);
            
            if (d < minDistance) {
                minDistance = d;
                colorKey = key;
            }
        }
    }
    return colorKey;
}
/*@{
                  @"blue": @{kId:    @(0xacc2d9)},
                  @"green": @{kId:    @(0x56ae57)},
                  @"dust": @{kId:    @(0xb2996e)},
//                      @"electric lime": @{kId:    @(0xa8ff04)},
                  @"green": @{kId:    @(0x69d84f)},
                  @"green": @{kId:    @(0x70b23f)},
                  @"blue": @{kId:    @(0xd4ffff)},
                  @"tea": @{kId:    @(0x65ab7c)},
                  @"purple": @{kId:    @(0x952e8f)},
                  @"yellow": @{kId:    @(0xfcfc81)},
//                      @"cement": @{kId:    @(0xa5a391)},
                  @"green": @{kId:    @(0x388004)},
//                      @"dusty teal": @{kId:    @(0x4c9085)},
                  @"grey": @{kId:    @(0x5e9b8a)},
//                      @"macaroni and cheese": @{kId:    @(0xefb435)},
                  @"pink": @{kId:    @(0xd99b82)},
//                      @"spruce": @{kId:    @(0x0a5f38)},
                  @"blue": @{kId:    @(0x0c06f7)},
                  @"green": @{kId:    @(0x61de2a)},
                  @"blue": @{kId:    @(0x3778bf)},
                  @"blue": @{kId:    @(0x2242c7)},
                  @"purple": @{kId:    @(0x533cc6)},
                  @"booger": @{kId:    @(0x9bb53c)},
                  @"green": @{kId:    @(0x05ffa6)},
                  @"blue": @{kId:    @(0x1f6357)},
//                      @"deep turquoise": @{kId:    @(0x017374)},
                  @"green": @{kId:    @(0x0cb577)},
                  @"pink": @{kId:    @(0xff0789)},
//                      @"bland": @{kId:    @(0xafa88b)},
//                      @"deep aqua": @{kId:    @(0x08787f)},
                  @"lavender": @{kId:    @(0xdd85d7)},
                  @"green": @{kId:    @(0xa6c875)},
                  @"green": @{kId:    @(0xa7ffb5)},
                  @"yellow": @{kId:    @(0xc2b709)},
                  @"pink": @{kId:    @(0xe78ea5)},
//                      @"deep lilac": @{kId:    @(0x966ebd)},
//                      @"desert": @{kId:    @(0xccad60)},
                  @"lavender": @{kId:    @(0xac86a8)},
                  @"grey": @{kId:    @(0x947e94)},
                  @"purply": @{kId:    @(0x983fb2)},
                  @"pink": @{kId:    @(0xff63e9)},
                  @"green": @{kId:    @(0xb2fba5)},
                  @"green": @{kId:    @(0x63b365)},
                  @"green": @{kId:    @(0x8ee53f)},
                  @"green": @{kId:    @(0xb7e1a1)},
                  @"pink": @{kId:    @(0xff6f52)},
                  @"green": @{kId:    @(0xbdf8a3)},
                  @"brown": @{kId:    @(0xd3b683)},
//                      @"egg shell": @{kId:    @(0xfffcc4)},
//                      @"eggplant purple": @{kId:    @(0x430541)},
                  @"pink": @{kId:    @(0xffb2d0)},
                  @"grey": @{kId:    @(0x997570)},
                  @"brown": @{kId:    @(0xad900d)},
//                      @"liliac": @{kId:    @(0xc48efd)},
                  @"blue": @{kId:    @(0x507b9c)},
                  @"brown": @{kId:    @(0x7d7103)},
//                      @"custard": @{kId:    @(0xfffd78)},
                  @"pink": @{kId:    @(0xda467d)},
                  @"brown": @{kId:    @(0x410200)},
//                      @"greenish beige": @{kId:    @(0xc9d179)},
                  @"manilla": @{kId:    @(0xfffa86)},
                  @"blue": @{kId:    @(0x5684ae)},
                  @"grey": @{kId:    @(0x6b7c85)},
                  @"green": @{kId:    @(0x6f6c0a)},
//                      @"bruise": @{kId:    @(0x7e4071)},
                  @"green": @{kId:    @(0x009337)},
                  @"yellow": @{kId:    @(0xd0e429)},
                  @"yellow": @{kId:    @(0xfff917)},
//                      @"azul": @{kId:    @(0x1d5dec)},
                  @"green": @{kId:    @(0x054907)},
                  @"green": @{kId:    @(0xb5ce08)},
                  @"lichen": @{kId:    @(0x8fb67b)},
                  @"gold": @{kId:    @(0xfdde6c)},
                  @"yellow": @{kId:    @(0xffdf22)},
                  @"burple": @{kId:    @(0x6832e3)},
                  @"butterscotch": @{kId:    @(0xfdb147)},
//                      @"toupe": @{kId:    @(0xc7ac7d)},
                  @"cream": @{kId:    @(0xfff39a)},
                  @"red": @{kId:    @(0x850e04)},
                  @"lavendar": @{kId:    @(0xefc0fe)},
                  @"grey": @{kId:    @(0x3c4142)},
                  @"squash": @{kId:    @(0xf2ab15)},
                  @"cinnamon": @{kId:    @(0xac4f06)},
                  @"sienna": @{kId:    @(0x9a6200)},
                  @"purple": @{kId:    @(0xca9bf7)},
                  @"cocoa": @{kId:    @(0x875f42)},
                  @"blue": @{kId:    @(0x3a2efe)},
                  @"orangeish": @{kId:    @(0xfd8d49)},
                  @"brown": @{kId:    @(0x8b3103)},
                  @"brown": @{kId:    @(0xcba560)},
                  @"swamp": @{kId:    @(0x698339)},
                  @"siena": @{kId:    @(0xb75203)},
                  @"camo": @{kId:    @(0x7f8f4e)},
                  @"blue": @{kId:    @(0x26538d)},
                  @"fern": @{kId:    @(0x63a950)},
                  @"rose": @{kId:    @(0xc87f89)},
                  @"pink": @{kId:    @(0xf6688e)},
//                      @"seafoam": @{kId:    @(0xa0febf)},
                  @"blue": @{kId:    @(0x7bf2da)},
                  @"orange": @{kId:    @(0xca6b02)},
                  @"blue": @{kId:    @(0x107ab0)},
//                      @"sapphire": @{kId:    @(0x2138ab)},
//                      @"greyish teal": @{kId:    @(0x719f91)},
                  @"yellow": @{kId:    @(0xfdb915)},
//                      @"parchment": @{kId:    @(0xfefcaf)},
//                      @"straw": @{kId:    @(0xfcf679)},
//                      @"very dark brown": @{kId:    @(0x1d0200)},
//                      @"terracota": @{kId:    @(0xcb6843)},
                  @"blue": @{kId:    @(0x31668a)},
                  @"blue": @{kId:    @(0x247afd)},
                  @"creme": @{kId:    @(0xffffb6)},
                  @"gold": @{kId:    @(0xfddc5c)},
                  @"blue": @{kId:    @(0x78d1b6)},
                  @"topaz": @{kId:    @(0x13bbaf)},
                  @"pink": @{kId:    @(0xfb5ffc)},
                  @"yellow": @{kId:    @(0xffe36e)},
                  @"blue": @{kId:    @(0x9d0759)},
                  @"blue": @{kId:    @(0x3a18b1)},
                  @"magenta": @{kId:    @(0xd767ad)},
                  @"purple": @{kId:    @(0x720058)},
                  @"yellow": @{kId:    @(0xffda03)},
                  @"leather": @{kId:    @(0xac7434)},
                  @"purple": @{kId:    @(0x9900fa)},
                  @"blue": @{kId:    @(0x02066f)},
                  @"hazel": @{kId:    @(0x8e7618)},
                  @"pink": @{kId:    @(0xd1768f)},
                  @"canary": @{kId:    @(0xfdff63)},
                  @"grey": @{kId:    @(0x95a3a6)},
//                      @"dark taupe": @{kId:    @(0x7f684e)},
                  @"purple": @{kId:    @(0x751973)},
                  @"pink": @{kId:    @(0xff6163)},
//                      @"dark sage": @{kId:    @(0x598556)},
                  @"blue": @{kId:    @(0x214761)},
                  @"blue": @{kId:    @(0x3c73a8)},
                  @"mushroom": @{kId:    @(0xba9e88)},
                  @"blue": @{kId:    @(0x021bf9)},
                  @"purple": @{kId:    @(0x734a65)},
                  @"khaki": @{kId:    @(0xe6f2a2)},
                  @"blue": @{kId:    @(0x4b57db)},
                  @"pink": @{kId:    @(0xd90166)},
                  @"blue": @{kId:    @(0x015482)},
                  @"carmine": @{kId:    @(0x9d0216)},
                  @"peach": @{kId:    @(0xffe5ad)},
                  @"purple": @{kId:    @(0x4e0550)},
                  @"golden": @{kId:    @(0xf9bc08)},
                  @"red": @{kId:    @(0xff073a)},
                  @"pink": @{kId:    @(0xc77986)},
                  @"blue": @{kId:    @(0xd6fffe)},
                  @"orange": @{kId:    @(0xfe4b03)},
                  @"grapefruit": @{kId:    @(0xfd5956)},
                  @"yellow": @{kId:    @(0xfce166)},
                  @"brown": @{kId:    @(0xb2713d)},
                  @"blue": @{kId:    @(0x1f3b4d)},
                  @"blue": @{kId:    @(0x56fca2)},
                  @"pink": @{kId:    @(0xfb5581)},
                  @"blue": @{kId:    @(0x3e82fc)},
                  @"ice": @{kId:    @(0xd6fffa)},
                  @"blue": @{kId:    @(0x4f738e)},
                  @"salmon": @{kId:    @(0xffb19a)},
                  @"algae": @{kId:    @(0x54ac68)},
//                      @"bluey grey": @{kId:    @(0x89a0b0)},
                  @"blue": @{kId:    @(0xcafffb)},
                  @"mint": @{kId:    @(0xb6ffbb)},
//                      @"raw umber": @{kId:    @(0xa75e09)},
                  @"blue": @{kId:    @(0x152eff)},
                  @"lavender": @{kId:    @(0x8d5eb7)},
//                      @"dull teal": @{kId:    @(0x5f9e8f)},
                  @"pink": @{kId:    @(0xfc86aa)},
                  @"wine": @{kId:    @(0x8c0034)},
                  @"brown": @{kId:    @(0xab7e4c)},
                  @"darkblue": @{kId:    @(0x030764)},
                  @"rosa": @{kId:    @(0xfe86a4)},
                  @"lipstick": @{kId:    @(0xd5174e)},
                  @"mauve": @{kId:    @(0xfed0fc)},
//                      @"claret": @{kId:    @(0x680018)},
//                      @"dandelion": @{kId:    @(0xfedf08)},
//                      @"orangered": @{kId:    @(0xfe420f)},
                  @"ruby": @{kId:    @(0xca0147)},
                  @"dark": @{kId:    @(0x1b2431)},
                  @"red": @{kId:    @(0xdb5856)},
                  @"yellow": @{kId:    @(0xddd618)},
                  @"cyan": @{kId:    @(0x41fdfe)},
                  @"coral": @{kId:    @(0xcf524e)},
                  @"red": @{kId:    @(0xa90308)},
                  @"brown": @{kId:    @(0x6e1005)},
                  @"pink": @{kId:    @(0xfe828c)},
                  @"putty": @{kId:    @(0xbeae8a)},
                  @"blue": @{kId:    @(0x0339f8)},
                  @"sand": @{kId:    @(0xa88f59)},
                  @"blue": @{kId:    @(0x5d21d0)},
                  @"saffron": @{kId:    @(0xfeb209)},
                  @"twilight": @{kId:    @(0x4e518b)},
                  @"brown": @{kId:    @(0x964e02)},
                  @"bluegrey": @{kId:    @(0x85a3b2)},
                  @"pink": @{kId:    @(0xff69af)},
                  @"blue": @{kId:    @(0xc3fbf4)},
                  @"petrol": @{kId:    @(0x005f6a)},
//                      @"royal": @{kId:    @(0x0c1793)},
                  @"butter": @{kId:    @(0xffff81)},
                  @"orange": @{kId:    @(0xf0833a)},
                  @"yellow": @{kId:    @(0xf1f33f)},
                  @"orange": @{kId:    @(0xfc824a)},
                  @"leaf": @{kId:    @(0x71aa34)},
                  @"grey": @{kId:    @(0xb7c9e2)},
                  @"blood": @{kId:    @(0x4b0101)},
                  @"purple": @{kId:    @(0xa552e6)},
                  @"red": @{kId:    @(0xaf2f0d)},
                  @"blue": @{kId:    @(0x8b88f8)},
                  @"sunflower": @{kId:    @(0xffc512)},
//                      @"velvet": @{kId:    @(0x750851)},
                  @"orange": @{kId:    @(0xc14a09)},
                  @"red": @{kId:    @(0xfe2f4a)},
                  @"blue": @{kId:    @(0x0203e2)},
                  @"blue": @{kId:    @(0x0a437a)},
                  @"red": @{kId:    @(0xa50055)},
                  @"brown": @{kId:    @(0xae8b0c)},
                  @"carnation": @{kId:    @(0xfd798f)},
                  @"yellow": @{kId:    @(0xbfac05)},
                  @"rose": @{kId:    @(0xc74767)},
                  @"red": @{kId:    @(0xb9484e)},
//                      @"grey/blue": @{kId:    @(0x647d8e)},
//                      @"lemon lime": @{kId:    @(0xbffe28)},
//                      @"purple/pink": @{kId:    @(0xd725de)},
                  @"yellow": @{kId:    @(0xb29705)},
                  @"brown": @{kId:    @(0x673a3f)},
                  @"wisteria": @{kId:    @(0xa87dc2)},
                  @"banana": @{kId:    @(0xfafe4b)},
                  @"lipstick": @{kId:    @(0xc0022f)},
                  @"blue": @{kId:    @(0x0e87cc)},
                  @"grey": @{kId:    @(0x8d8468)},
                  @"purple": @{kId:    @(0xad03de)},
                  @"blue": @{kId:    @(0xc4fff7)},
                  @"sandy": @{kId:    @(0xfdee73)},
                  @"pale": @{kId:    @(0xfff9d0)},
//                      @"blue/grey": @{kId:    @(0x758da3)},
                  @"magenta": @{kId:    @(0xf504c9)},
                  @"greyblue": @{kId:    @(0x77a1b5)},
                  @"purpley": @{kId:    @(0x8756e4)},
                  @"pink": @{kId:    @(0xc27e79)},
//                      @"dark aquamarine": @{kId:    @(0x017371)},
//                      @"diarrhea": @{kId:    @(0x9f8303)},
                  @"mustard": @{kId:    @(0xf7d560)},
                  @"blue": @{kId:    @(0xbdf6fe)},
                  @"olive": @{kId:    @(0x9cbb04)},
                  @"blue": @{kId:    @(0x29465b)},
                  @"periwinkle": @{kId:    @(0xc1c6fc)},
                  @"sunshine": @{kId:    @(0xfffd37)},
                  @"purple": @{kId:    @(0xa442a0)},
                  @"pink": @{kId:    @(0xf36196)},
                  @"brown": @{kId:    @(0x947706)},
                  @"pink": @{kId:    @(0xfff4f2)},
                  @"viridian": @{kId:    @(0x1e9167)},
                  @"bile": @{kId:    @(0xb5c306)},
                  @"yellow": @{kId:    @(0xfeff7f)},
                  @"lime": @{kId:    @(0x87fd05)},
//                      @"spearmint": @{kId:    @(0x1ef876)},
//                      @"aquamarine": @{kId:    @(0x7bfdc7)},
                  @"sage": @{kId:    @(0xbcecac)},
//                      @"baby poo": @{kId:    @(0xab9004)},
                  @"seafoam": @{kId:    @(0x1fb57a)},
//                      @"deep teal": @{kId:    @(0x00555a)},
                  @"heather": @{kId:    @(0xa484ac)},
                  @"rust": @{kId:    @(0xc45508)},
                  @"blue": @{kId:    @(0x3f829d)},
                  @"lilac": @{kId:    @(0xc95efb)},
                  @"blue": @{kId:    @(0x016795)},
                  @"orange": @{kId:    @(0xf0944d)},
                  @"grape": @{kId:    @(0x5d1451)},
                  @"lime": @{kId:    @(0xd0fe1d)},
                  @"mango": @{kId:    @(0xffa62b)},
//                      @"shamrock": @{kId:    @(0x01b44c)},
//                      @"bubblegum": @{kId:    @(0xff6cb5)},
                  @"brown": @{kId:    @(0x6b4247)},
                  @"yellow": @{kId:    @(0xc7c10c)},
                  @"cyan": @{kId:    @(0xb7fffa)},
                  @"lime": @{kId:    @(0xaeff6e)},
                  @"tomato": @{kId:    @(0xec2d01)},
                  @"merlot": @{kId:    @(0x730039)},
                  @"night": @{kId:    @(0x040348)},
                  @"pink": @{kId:    @(0xdf4ec8)},
                  @"apple": @{kId:    @(0x6ecb3c)},
                  @"heliotrope": @{kId:    @(0xd94ff5)},
//                      @"yellow/green": @{kId:    @(0xc8fd3d)},
                  @"black": @{kId:    @(0x070d0d)},
                  @"blue": @{kId:    @(0x4984b8)},
                  @"brown": @{kId:    @(0xac7e04)},
                  @"dusk": @{kId:    @(0x4e5481)},
                  @"brown": @{kId:    @(0x876e4b)},
                  @"kiwi": @{kId:    @(0x9cef43)},
//                      @"seaweed": @{kId:    @(0x18d17b)},
                  @"blue": @{kId:    @(0x1805db)},
                  @"iris": @{kId:    @(0x6258c4)},
                  @"orange": @{kId:    @(0xff964f)},
                  @"orange": @{kId:    @(0xffab0f)},
                  @"perrywinkle": @{kId:    @(0x8f8ce7)},
                  @"tealish": @{kId:    @(0x24bca8)},
                  @"plum": @{kId:    @(0x3f012c)},
                  @"pear": @{kId:    @(0xcbf85f)},
                  @"orange": @{kId:    @(0xff724c)},
                  @"purple": @{kId:    @(0x280137)},
                  @"urple": @{kId:    @(0xb36ff6)},
                  @"mint": @{kId:    @(0x48c072)},
                  @"burgundy": @{kId:    @(0xa8415b)},
                  @"blue": @{kId:    @(0x06b1c4)},
                  @"sandy": @{kId:    @(0xf1da7a)},
                  @"Pink": @{kId:    @(0xff0490)},
                  @"purple": @{kId:    @(0x805b87)},
                  @"greyish": @{kId:    @(0xa8a495)},
                  @"yellow": @{kId:    @(0xcfff04)},
                  @"banana": @{kId:    @(0xffff7e)},
                  @"pink": @{kId:    @(0xff7fa7)},
                  @"tomato": @{kId:    @(0xef4026)},
                  @"sea": @{kId:    @(0x3c9992)},
                  @"brown": @{kId:    @(0x886806)},
                  @"buff": @{kId:    @(0xfef69e)},
                  @"fawn": @{kId:    @(0xcfaf7b)},
                  @"blue": @{kId:    @(0x3b719f)},
                  @"rose": @{kId:    @(0xfdc1c5)},
                  @"amethyst": @{kId:    @(0x9b5fc0)},
                  @"blue": @{kId:    @(0x0f9b8e)},
                  @"chestnut": @{kId:    @(0x742802)},
                  @"pea": @{kId:    @(0xa4bf20)},
                  @"orange": @{kId:    @(0xcd5909)},
                  @"stone": @{kId:    @(0xada587)},
                  @"rose": @{kId:    @(0xbe013c)},
                  @"aqua": @{kId:    @(0xb8ffeb)},
                  @"orange": @{kId:    @(0xdc4d01)},
                  @"earth": @{kId:    @(0xa2653e)},
                  @"blue": @{kId:    @(0x9dbcd4)},
                  @"grey": @{kId:    @(0xfdfdfe)},
                  @"asparagus": @{kId:    @(0x77ab56)},
                  @"blueberry": @{kId:    @(0x464196)},
                  @"red": @{kId:    @(0x990147)},
                  @"lime": @{kId:    @(0xbefd73)},
                  @"greenish": @{kId:    @(0x32bf84)},
                  @"caramel": @{kId:    @(0xaf6f09)},
                  @"magenta": @{kId:    @(0xa0025c)},
                  @"peach": @{kId:    @(0xffd8b1)},
                  @"chocolate": @{kId:    @(0x7f4e1e)},
                  @"ocher": @{kId:    @(0xbf9b0c)},
                  @"blue": @{kId:    @(0x7bc8f6)},
                  @"blue": @{kId:    @(0x475f94)},
                  @"golden": @{kId:    @(0xf5bf03)},
                  @"beige": @{kId:    @(0xfffeb6)},
                  @"yellow": @{kId:    @(0xfffd74)},
                  @"purple": @{kId:    @(0x895b7b)},
                  @"blue": @{kId:    @(0x436bad)},
                  @"yellow": @{kId:    @(0xd0c101)},
                  @"yellow": @{kId:    @(0xc6f808)},
                  @"red": @{kId:    @(0xf43605)},
                  @"brown": @{kId:    @(0xb25f03)},
                  @"green": @{kId:    @(0x2a7e19)},
                  @"violet": @{kId:    @(0x490648)},
                  @"gunmetal": @{kId:    @(0x536267)},
                  @"blue": @{kId:    @(0x5a06ef)},
                  @"cherry": @{kId:    @(0xcf0234)},
                  @"brown": @{kId:    @(0xc4a661)},
                  @"grey": @{kId:    @(0x978a84)},
                  @"indigo": @{kId:    @(0x1f0954)},
                  @"midnight": @{kId:    @(0x03012d)},
                  @"purple": @{kId:    @(0xa66fb5)},
                  @"blood": @{kId:    @(0x770001)},
                  @"red": @{kId:    @(0x922b05)},
                  @"grey": @{kId:    @(0x7d7f7c)},
                  @"berry": @{kId:    @(0x990f4b)},
                  @"poo": @{kId:    @(0x8f7303)},
                  @"pink": @{kId:    @(0xc83cb9)},
                  @"salmon": @{kId:    @(0xfea993)},
                  @"snot": @{kId:    @(0xacbb0d)},
                  @"easter": @{kId:    @(0xc071fe)},
//                      @"light yellow green": @{kId:    @(0xccfd7f)},
                  @"blue": @{kId:    @(0x00022e)},
                  @"drab": @{kId:    @(0x828344)},
                  @"rose": @{kId:    @(0xffc5cb)},
                  @"rouge": @{kId:    @(0xab1239)},
                  @"red": @{kId:    @(0xb0054b)},
                  @"poop": @{kId:    @(0x937c00)},
                  @"green": @{kId:    @(0x019529)},
                  @"navy": @{kId:    @(0x000435)},
                  @"blue": @{kId:    @(0x42b395)},
                  @"plum": @{kId:    @(0x9d5783)},
                  @"grey": @{kId:    @(0xc8aca9)},
                  @"orange": @{kId:    @(0xc87606)},
                  @"red": @{kId:    @(0xaa2704)},
//                      @"pale lilac": @{kId:    @(0xe4cbff)},
                  @"red": @{kId:    @(0xfa4224)},
                  @"blue": @{kId:    @(0x0804f9)},
                  @"purple": @{kId:    @(0x76424e)},
                  @"wheat": @{kId:    @(0xfbdd7e)},
                  @"purple": @{kId:    @(0x2a0134)},
                  @"watermelon": @{kId:    @(0xfd4659)},
                  @"blue": @{kId:    @(0x0d75f8)},
                  @"Red": @{kId:    @(0xfe0002)},
                  @"Yellow": @{kId:    @(0xcb9d06)},
                  @"Orange": @{kId:    @(0xfb7d07)},
                  @"olive": @{kId:    @(0xb9cc81)},
                  @"lilac": @{kId:    @(0xedc8ff)},
                  @"blue": @{kId:    @(0x8ab8fe)},
                  @"mulberry": @{kId:    @(0x920a4e)},
                  @"auburn": @{kId:    @(0x9a3001)},
                  @"celadon": @{kId:    @(0xbefdb7)},
                  @"brown": @{kId:    @(0xb17261)},
                  @"brown": @{kId:    @(0x885f01)},
                  @"blue": @{kId:    @(0x02ccfe)},
                  @"celery": @{kId:    @(0xc1fd95)},
                  @"brown": @{kId:    @(0x836539)},
                  @"strawberry": @{kId:    @(0xfb2943)},
                  @"lime": @{kId:    @(0x84b701)},
                  @"copper": @{kId:    @(0xb66325)},
                  @"brown": @{kId:    @(0x7f5112)},
                  @"egg": @{kId:    @(0x6dedfd)},
                  @"aqua": @{kId:    @(0x0bf9ea)},
                  @"lavender": @{kId:    @(0xc760ff)},
                  @"ivory": @{kId:    @(0xffffcb)},
                  @"navy": @{kId:    @(0x155084)},
                  @"brown": @{kId:    @(0x645403)},
                  @"brown": @{kId:    @(0x7a5901)},
                  @"blue": @{kId:    @(0x000133)},
                  @"blue": @{kId:    @(0x2e5a88)},
                  @"adobe": @{kId:    @(0xbd6c48)},
                  @"barney": @{kId:    @(0xac1db8)},
                  @"blue": @{kId:    @(0x26f7fd)},
                  @"lime": @{kId:    @(0xaefd6c)},
                  @"khaki": @{kId:    @(0x9b8f55)},
                  @"orange": @{kId:    @(0xffad01)},
                  @"ocre": @{kId:    @(0xc69c04)},
                  @"maize": @{kId:    @(0xf4d054)},
                  @"green": @{kId:    @(0x05480d)},
                  @"sandstone": @{kId:    @(0xc9ae74)},
                  @"brown": @{kId:    @(0x60460f)},
                  @"blue": @{kId:    @(0x8af1fe)},
                  @"marine": @{kId:    @(0x2ee8bb)},
                  @"pink": @{kId:    @(0xfdb0c0)},
                  @"brown": @{kId:    @(0xb16002)},
                  @"red": @{kId:    @(0xf7022a)},
                  @"yellow": @{kId:    @(0xd5ab09)},
                  @"grey": @{kId:    @(0x86775f)},
                  @"camel": @{kId:    @(0xc69f59)},
                  @"grey": @{kId:    @(0x7a687f)},
                  @"marine": @{kId:    @(0x042e60)},
                  @"pink": @{kId:    @(0xc88d94)},
                  @"turquoise": @{kId:    @(0xa5fbd5)},
                  @"yellow": @{kId:    @(0xfffe71)},
                  @"purple": @{kId:    @(0x6241c7)},
                  @"yellow": @{kId:    @(0xfffe40)},
                  @"red": @{kId:    @(0xd3494e)},
                  @"sepia": @{kId:    @(0x985e2b)},
                  @"coffee": @{kId:    @(0xa6814c)},
                  @"magenta": @{kId:    @(0xff08e8)},
                  @"mocha": @{kId:    @(0x9d7651)},
                  @"ecru": @{kId:    @(0xfeffca)},
                  @"purpleish": @{kId:    @(0x98568d)},
                  @"cranberry": @{kId:    @(0x9e003a)},
                  @"orange": @{kId:    @(0xb96902)},
                  @"rose": @{kId:    @(0xba6873)},
                  @"melon": @{kId:    @(0xff7855)},
                  @"silver": @{kId:    @(0xc5c9c7)},
                  @"blue": @{kId:    @(0x661aee)},
                  @"blue": @{kId:    @(0x6140ef)},
                  @"brown": @{kId:    @(0x7b5804)},
                  @"blue": @{kId:    @(0x276ab3)},
                  @"amber": @{kId:    @(0xfeb308)},
                  @"blue": @{kId:    @(0x6488ea)},
                  @"blue": @{kId:    @(0x056eee)},
                  @"brown": @{kId:    @(0xb27a01)},
                  @"turquoise": @{kId:    @(0x0ffef9)},
                  @"purple": @{kId:    @(0x820747)},
                  @"brown": @{kId:    @(0x7a6a4f)},
//                      @"vermillion": @{kId:    @(0xf4320c)},
                  @"russet": @{kId:    @(0xa13905)},
                  @"grey": @{kId:    @(0x6f828a)},
                  @"purple": @{kId:    @(0xa55af4)},
                  @"violet": @{kId:    @(0xad0afd)},
                  @"blue": @{kId:    @(0x004577)},
                  @"blue": @{kId:    @(0x005249)},
                  @"pine": @{kId:    @(0x2b5d34)},
                  @"gold": @{kId:    @(0xb59410)},
                  @"bluish": @{kId:    @(0x2976bb)},
                  @"blue": @{kId:    @(0x014182)},
                  @"red": @{kId:    @(0xbb3f3f)},
                  @"bronze": @{kId:    @(0xa87900)},
                  @"teal": @{kId:    @(0x82cbb2)},
                  @"pink": @{kId:    @(0xfe46a5)},
                  @"pink": @{kId:    @(0xfe83cc)},
                  @"mustard": @{kId:    @(0xa88905)},
                  @"shit": @{kId:    @(0x7f5f00)},
                  @"purple": @{kId:    @(0x9e43a2)},
                  @"dirt": @{kId:    @(0x8a6e45)},
                  @"pink": @{kId:    @(0xcc7a8b)},
                  @"violet": @{kId:    @(0x9e0168)},
                  @"yellow": @{kId:    @(0xfdff38)},
                  @"pistachio": @{kId:    @(0xc0fa8b)},
                  @"yellow": @{kId:    @(0xeedc5b)},
                  @"blue": @{kId:    @(0x3b5b92)},
                  @"blue": @{kId:    @(0x01889f)},
                  @"blue": @{kId:    @(0x3d7afd)},
                  @"blue": @{kId:    @(0x5f34e7)},
                  @"indigo": @{kId:    @(0x6d5acf)},
                  @"maroon": @{kId:    @(0x3c0008)},
                  @"purple": @{kId:    @(0xcb00f5)},
                  @"blue": @{kId:    @(0x658cbb)},
                  @"green": @{kId:    @(0x749551)},
                  @"green": @{kId:    @(0x9dc100)},
                  @"yellowish": @{kId:    @(0xfaee66)},
                  @"bordeaux": @{kId:    @(0x7b002c)},
                  @"mauve": @{kId:    @(0xc292a1)},
                  @"ocean": @{kId:    @(0x017b92)},
                  @"marigold": @{kId:    @(0xfcc006)},
                  @"orange": @{kId:    @(0xd8863b)},
                  @"steel": @{kId:    @(0x738595)},
                  @"Purple": @{kId:    @(0xaa23ff)},
                  @"brown": @{kId:    @(0x9b7a01)},
                  @"blush": @{kId:    @(0xf29e8e)},
                  @"orange": @{kId:    @(0xff5b00)},
                  @"lemon": @{kId:    @(0xfdff52)},
                  @"grey": @{kId:    @(0x866f85)},
                  @"lavender": @{kId:    @(0xeecffe)},
                  @"blue": @{kId:    @(0x510ac9)},
                  @"red": @{kId:    @(0x9f2305)},
                  @"cerise": @{kId:    @(0xde0c62)},
                  @"purple": @{kId:    @(0x916e99)},
                  @"apricot": @{kId:    @(0xffb16d)},
                  @"brown": @{kId:    @(0x7f7053)},
                  @"grey": @{kId:    @(0x77926f)},
                  @"violet": @{kId:    @(0xceaefa)},
                  @"blue": @{kId:    @(0x8f99fb)},
                  @"sky": @{kId:    @(0xc6fcff)},
//                      @"blurple": @{kId:    @(0x5539cc)},
                  @"brown": @{kId:    @(0x544e03)},
                  @"bluegreen": @{kId:    @(0x017a79)},
                  @"teal": @{kId:    @(0x01f9c6)},
                  @"yellow": @{kId:    @(0xc9b003)},
                  @"soup": @{kId:    @(0x929901)},
                  @"forest": @{kId:    @(0x0b5509)},
                  @"purple": @{kId:    @(0xa00498)},
//                      @"ultramarine": @{kId:    @(0x2000b1)},
                  @"purplish": @{kId:    @(0x94568c)},
                  @"yellow": @{kId:    @(0xc2be0e)},
                  @"grey": @{kId:    @(0x748b97)},
                  @"periwinkle": @{kId:    @(0x665fd1)},
                  @"lilac": @{kId:    @(0x9c6da5)},
                  @"reddish": @{kId:    @(0xc44240)},
                  @"maroon": @{kId:    @(0xa24857)},
                  @"purple": @{kId:    @(0x825f87)},
                  @"cotta": @{kId:    @(0xc9643b)},
                  @"avocado": @{kId:    @(0x90b134)},
                  @"blue": @{kId:    @(0x01386a)},
                  @"grey": @{kId:    @(0x59656d)},
                  @"green": @{kId:    @(0x21fc0d)},
                  @"blue": @{kId:    @(0x5a86ad)},
                  @"yellow": @{kId:    @(0xfec615)},
                  @"yellow": @{kId:    @(0xfffd01)},
                  @"lavender": @{kId:    @(0xdfc5fe)},
                  @"umber": @{kId:    @(0xb26400)},
                  @"poop": @{kId:    @(0x7f5e00)},
                  @"peach": @{kId:    @(0xde7e5d)},
                  @"eggshell": @{kId:    @(0xffffd4)},
                  @"denim": @{kId:    @(0x3b638c)},
                  @"brown": @{kId:    @(0xb79400)},
                  @"purple": @{kId:    @(0x84597e)},
                  @"brown": @{kId:    @(0x411900)},
                  @"wine": @{kId:    @(0x7b0323)},
                  @"blue": @{kId:    @(0x04d9ff)},
                  @"tan": @{kId:    @(0xfbeeac)},
                  @"blue": @{kId:    @(0xd7fffe)},
                  @"blue": @{kId:    @(0x4e7496)},
                  @"mauve": @{kId:    @(0x874c62)},
                  @"blue": @{kId:    @(0xd5ffff)},
                  @"purple": @{kId:    @(0x826d8c)},
                  @"pink": @{kId:    @(0xffbacd)},
                  @"sky": @{kId:    @(0x448ee4)},
                  @"evergreen": @{kId:    @(0x05472a)},
                  @"pink": @{kId:    @(0xd5869d)},
                  @"aubergine": @{kId:    @(0x3d0734)},
                  @"mahogany": @{kId:    @(0x4a0100)},
                  @"orange": @{kId:    @(0xf8481c)},
                  @"pink": @{kId:    @(0xe03fd8)},
                  @"pink": @{kId:    @(0xd58a94)},
                  @"purple": @{kId:    @(0xc94cbe)},
                  @"purple": @{kId:    @(0xdb4bda)},
                  @"red": @{kId:    @(0x9e3623)},
                  @"rose": @{kId:    @(0xb5485d)},
                  @"mud": @{kId:    @(0x735c12)},
                  @"brownish": @{kId:    @(0x9c6d57)},
                  @"brown": @{kId:    @(0xb1916e)},
                  @"blue": @{kId:    @(0x49759c)},
                  @"umber": @{kId:    @(0xa0450e)},
                  @"clay": @{kId:    @(0xb66a50)},
                  @"aqua": @{kId:    @(0x8cffdb)},
                  @"orange": @{kId:    @(0xcb7723)},
                  @"aqua": @{kId:    @(0x05696b)},
                  @"pink": @{kId:    @(0xce5dae)},
                  @"salmon": @{kId:    @(0xc85a53)},
                  @"grey": @{kId:    @(0x96ae8d)},
                  @"jade": @{kId:    @(0x1fa774)},
                  @"beige": @{kId:    @(0xac9362)},
//                      @"emerald": @{kId:    @(0x01a049)},
                  @"red": @{kId:    @(0xd9544d)},
                  @"magenta": @{kId:    @(0xfa5ff7)},
                  @"sky": @{kId:    @(0x82cafc)},
                  @"cyan": @{kId:    @(0xacfffc)},
                  @"orange": @{kId:    @(0xfcb001)},
                  @"purple": @{kId:    @(0x910951)},
                  @"pink": @{kId:    @(0xfe2c54)},
                  @"orchid": @{kId:    @(0xc875c4)},
                  @"yellow": @{kId:    @(0xcdc50a)},
                  @"red": @{kId:    @(0xfd411e)},
                  @"red": @{kId:    @(0x9a0200)},
                  @"brown": @{kId:    @(0xbe6400)},
                  @"blue": @{kId:    @(0x030aa7)},
                  @"pink": @{kId:    @(0xfe019a)},
                  @"pink": @{kId:    @(0xf7879a)},
                  @"purple": @{kId:    @(0x887191)},
                  @"raspberry": @{kId:    @(0xb00149)},
                  @"green": @{kId:    @(0x12e193)},
                  @"pink": @{kId:    @(0xfe7b7c)},
                  @"tangerine": @{kId:    @(0xff9408)},
                  @"brown": @{kId:    @(0x8b2e16)},
                  @"brown": @{kId:    @(0x696112)},
                  @"pumpkin": @{kId:    @(0xe17701)},
                  @"charcoal": @{kId:    @(0x343837)},
                  @"pink": @{kId:    @(0xffb7ce)},
//                      @"cornflower": @{kId:    @(0x6a79f7)},
                  @"violet": @{kId:    @(0x5d06e9)},
                  @"chocolate": @{kId:    @(0x3d1c02)},
                  @"scarlet": @{kId:    @(0xbe0119)},
                  @"yellow": @{kId:    @(0xc9ff27)},
                  @"olive": @{kId:    @(0x373e02)},
                  @"sienna": @{kId:    @(0xa9561e)},
                  @"purple": @{kId:    @(0xcaa0ff)},
                  @"terracotta": @{kId:    @(0xca6641)},
                  @"blue": @{kId:    @(0x02d8e9)},
                  @"blood": @{kId:    @(0x980002)},
                  @"pink": @{kId:    @(0xcb0162)},
                  @"green": @{kId:    @(0x5cac2d)},
                  @"moss": @{kId:    @(0x769958)},
                  @"tan": @{kId:    @(0xaf884a)},
                  @"orange": @{kId:    @(0xffa756)},
                  @"vomit": @{kId:    @(0xa2a415)},
                  @"lavender": @{kId:    @(0x856798)},
                  @"violet": @{kId:    @(0x34013f)},
                  @"blue": @{kId:    @(0x632de9)},
                  @"cyan": @{kId:    @(0x0a888a)},
                  @"olive": @{kId:    @(0x6f7632)},
                  @"pinkish": @{kId:    @(0xd46a7e)},
                  @"cobalt": @{kId:    @(0x1e488f)},
                  @"purple": @{kId:    @(0xbc13fe)},
                  @"turquoise": @{kId:    @(0x7ef4cc)},
                  @"wine": @{kId:    @(0x80013f)},
                  @"blue": @{kId:    @(0xb1d1fc)},
                  @"white": @{kId:    @(0xffffe4)},
                  @"blue": @{kId:    @(0x0652ff)},
                  @"turquoise": @{kId:    @(0x045c5a)},
                  @"blue": @{kId:    @(0x5729ce)},
//                      @"azure": @{kId:    @(0x069af3)},
                  @"red": @{kId:    @(0xff000d)},
                  @"red": @{kId:    @(0xf10c45)},
                  @"blue": @{kId:    @(0x5170d7)},
                  @"olive": @{kId:    @(0xacbf69)},
                  @"grape": @{kId:    @(0x6c3461)},
                  @"blue": @{kId:    @(0x5e819d)},
                  @"blue": @{kId:    @(0x601ef9)},
                  @"yellow": @{kId:    @(0xcdfd02)},
                  @"blue": @{kId:    @(0x2c6fbb)},
                  @"rose": @{kId:    @(0xc0737a)},
                  @"violet": @{kId:    @(0xd6b4fc)},
                  @"blue": @{kId:    @(0x020035)},
                  @"purple": @{kId:    @(0x703be7)},
                  @"orange": @{kId:    @(0xfd3c06)},
                  @"magenta": @{kId:    @(0x960056)},
                  @"greenish": @{kId:    @(0x40a368)},
                  @"ocean": @{kId:    @(0x03719c)},
                  @"coral": @{kId:    @(0xfc5a50)},
                  @"cream": @{kId:    @(0xffffc2)},
                  @"brown": @{kId:    @(0x7f2b0a)},
                  @"sienna": @{kId:    @(0xb04e0f)},
                  @"brick": @{kId:    @(0xa03623)},
                  @"sage": @{kId:    @(0x87ae73)},
                  @"green": @{kId:    @(0x789b73)},
                  @"white": @{kId:    @(0xffffff)},
                  @"blue": @{kId:    @(0x98eff9)},
                  @"green": @{kId:    @(0x658b38)},
                  @"blue": @{kId:    @(0x5a7d9a)},
                  @"eggplant": @{kId:    @(0x380835)},
                  @"yellow": @{kId:    @(0xfffe7a)},
                  @"green": @{kId:    @(0x5ca904)},
                  @"grey": @{kId:    @(0xd8dcd6)},
                  @"puke": @{kId:    @(0xa5a502)},
                  @"purple": @{kId:    @(0xd648d7)},
                  @"blue": @{kId:    @(0x047495)},
                  @"purple": @{kId:    @(0xb790d4)},
                  @"blue": @{kId:    @(0x5b7c99)},
                  @"grey": @{kId:    @(0x607c8e)},
                  @"green": @{kId:    @(0x0b4008)},
//                      @"fuchsia": @{kId:    @(0xed0dd9)},
//                      @"crimson": @{kId:    @(0x8c000f)},
                  @"yellow": @{kId:    @(0xffff84)},
                  @"ochre": @{kId:    @(0xbf9005)},
                  @"yellow": @{kId:    @(0xd2bd0a)},
                  @"red": @{kId:    @(0xff474c)},
//                      @"cerulean": @{kId:    @(0x0485d1)},
                  @"pink": @{kId:    @(0xffcfdc)},
                  @"blue": @{kId:    @(0x040273)},
                  @"rust": @{kId:    @(0xa83c09)},
//                      @"teal": @{kId:    @(0x90e4c1)},
//                      @"slate": @{kId:    @(0x516572)},
                  @"goldenrod": @{kId:    @(0xfac205)},
                  @"yellow": @{kId:    @(0xd5b60a)},
                  @"grey": @{kId:    @(0x363737)},
                  @"green": @{kId:    @(0x4b5d16)},
                  @"blue": @{kId:    @(0x6b8ba4)},
                  @"seafoam": @{kId:    @(0x80f9ad)},
                  @"puce": @{kId:    @(0xa57e52)},
                  @"green": @{kId:    @(0xa9f971)},
                  @"orange": @{kId:    @(0xc65102)},
                  @"sand": @{kId:    @(0xe2ca76)},
                  @"green": @{kId:    @(0xb0ff9d)},
                  @"mint": @{kId:    @(0x9ffeb0)},
                  @"orange": @{kId:    @(0xfdaa48)},
                  @"pink": @{kId:    @(0xfe01b1)},
                  @"chartreuse": @{kId:    @(0xc1f80a)},
                  @"purple": @{kId:    @(0x36013f)},
                  @"brown": @{kId:    @(0x341c02)},
                  @"taupe": @{kId:    @(0xb9a281)},
                  @"green": @{kId:    @(0x8eab12)},
                  @"green": @{kId:    @(0x9aae07)},
                  @"green": @{kId:    @(0x02ab2e)},
                  @"green": @{kId:    @(0x7af9ab)},
                  @"green": @{kId:    @(0x137e6d)},
                  @"khaki": @{kId:    @(0xaaa662)},
                  @"burgundy": @{kId:    @(0x610023)},
                  @"teal": @{kId:    @(0x014d4e)},
                  @"red": @{kId:    @(0x8f1402)},
                  @"purple": @{kId:    @(0x4b006e)},
                  @"plum": @{kId:    @(0x580f41)},
                  @"green": @{kId:    @(0x8fff9f)},
                  @"gold": @{kId:    @(0xdbb40c)},
                  @"blue": @{kId:    @(0xa2cffe)},
                  @"green": @{kId:    @(0xc0fb2d)},
                  @"purple": @{kId:    @(0xbe03fd)},
                  @"red": @{kId:    @(0x840000)},
                  @"blue": @{kId:    @(0xd0fefe)},
                  @"navy": @{kId:    @(0x01153e)},
                  @"aquamarine": @{kId:    @(0x04d8b2)},
                  @"orange": @{kId:    @(0xc04e01)},
                  @"blue": @{kId:    @(0x0165fc)},
                  @"rose": @{kId:    @(0xcf6275)},
                  @"pink": @{kId:    @(0xffd1df)},
                  @"mustard": @{kId:    @(0xceb301)},
                  @"indigo": @{kId:    @(0x380282)},
//                      @"lime": @{kId:    @(0xaaff32)},
                  @"periwinkle": @{kId:    @(0x8e82fe)},
                  @"pink": @{kId:    @(0xcb416b)},
                  @"green": @{kId:    @(0x677a04)},
                  @"peach": @{kId:    @(0xffb07c)},
                  @"green": @{kId:    @(0xc7fdb5)},
                  @"brown": @{kId:    @(0xad8150)},
                  @"pink": @{kId:    @(0xff028d)},
                  @"black": @{kId:    @(0x000000)},
                  @"lilac": @{kId:    @(0xcea2fd)},
                  @"blue": @{kId:    @(0x001146)},
                  @"blue": @{kId:    @(0x0504aa)},
                  @"beige": @{kId:    @(0xe6daa6)},
                  @"salmon": @{kId:    @(0xff796c)},
                  @"olive": @{kId:    @(0x6e750e)},
                  @"maroon": @{kId:    @(0x650021)},
                  @"green": @{kId:    @(0x01ff07)},
                  @"purple": @{kId:    @(0x35063e)},
                  @"mauve": @{kId:    @(0xae7181)},
                  @"aqua": @{kId:    @(0x13eac9)},
                  @"cyan": @{kId:    @(0x00ffff)},
                  @"tan": @{kId:    @(0xd1b26f)},
                  @"blue": @{kId:    @(0x00035b)},
                  @"lavender": @{kId:    @(0xc79fef)},
                  @"turquoise": @{kId:    @(0x06c2ac)},
                  @"violet": @{kId:    @(0x9a0eea)},
                  @"purple": @{kId:    @(0xbf77f6)},
                  @"grey": @{kId:    @(0x929591)},
//                      @"sky": @{kId:    @(0x75bbfd)},
                  @"yellow": @{kId:    @(0xffff14)},
                  @"magenta": @{kId:    @(0xc20078)},
                  @"orange": @{kId:    @(0xf97306)},
                  @"teal": @{kId:    @(0x029386)},
                  @"blue": @{kId:    @(0x95d0fc)},
                  @"red": @{kId:    @(0xe50000)},
                  @"brown": @{kId:    @(0x653700)},
                  @"pink": @{kId:    @(0xff81c0)},
                  @"blue": @{kId:    @(0x0343df)},
                  @"green": @{kId:    @(0x15b01a)},
                  @"purple": @{kId:    @(0x7e1e9c)},
                  }
*/
@end
